version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Mount the custom config file
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]  # Use the custom config file

volumes:
  redis_data:
    driver: local

networks:
  default:
    driver: bridge
