from enum import Enum

class EnvKeys(Enum):
    APP_HOST='APP_HOST'
    APP_PORT='APP_PORT'
    APP_ENVIRONMENT = "APP_ENVIRONMENT"
    # LLM
    APP_OPENAI_KEY = 'APP_OPENAI_KEY'
    APP_OPENAI_TEMPERATURE = 'APP_OPENAI_TEMPERATURE'
    # Logging settings
    LOG_LEVEL='LOG_LEVEL'
    LOG_FILE='LOG_FILE'
    APP_LOGGING_LEVEL='APP_LOGGING_LEVEL'
    APP_LOGGING_HANDLER_NAME='APP_LOGGING_HANDLER_NAME'
    APP_LOGGING_FILE='APP_LOGGING_FILE'
    APP_LOGGING_FORMATTER='APP_LOGGING_FORMATTER'
    APP_LOGGING_DATEFORMAT='APP_LOGGING_DATEFORMAT'
    APP_LOGGING_MAXBYTES='APP_LOGGING_MAXBYTES'
    APP_LOGGING_BACKUPCOUNT='APP_LOGGING_BACKUPCOUNT'
    # Authentication
    SECRET_KEY='SECRET_KEY'
    ALGORITHM='ALGORITHM'
    ACCESS_TOKEN_EXPIRE_MINUTES='ACCESS_TOKEN_EXPIRE_MINUTES'